# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'area.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from square_area import UiForm
from circle_area import UForm
from triagnle_area import iForm
from rectangle_area import U_Form

class area(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(470, 400)
        Form.setMinimumSize(QtCore.QSize(470, 400))
        Form.setMaximumSize(QtCore.QSize(470, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/area.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(161, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 50, 120, 141))
        self.widget.setObjectName("widget")
        self.square = QtWidgets.QPushButton(self.widget)
        self.square.setGeometry(QtCore.QRect(0, 0, 121, 131))
        font = QtGui.QFont()
        self.square.setFont(font)
        self.square.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.square.setIcon(icon1)
        self.square.setIconSize(QtCore.QSize(124, 135))
        self.square.setFlat(True)
        self.square.setObjectName("square")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 102, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(181, 50, 120, 141))
        self.widget_2.setObjectName("widget_2")
        self.circle = QtWidgets.QPushButton(self.widget_2)
        self.circle.setGeometry(QtCore.QRect(0, 0, 121, 131))
        font = QtGui.QFont()
        self.circle.setFont(font)
        self.circle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circle.setIcon(icon2)
        self.circle.setIconSize(QtCore.QSize(104, 86))
        self.circle.setFlat(True)
        self.circle.setObjectName("circle")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 102, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(330, 50, 120, 141))
        self.widget_3.setObjectName("widget_3")
        self.triangle = QtWidgets.QPushButton(self.widget_3)
        self.triangle.setGeometry(QtCore.QRect(0, 0, 121, 131))
        font = QtGui.QFont()
        self.triangle.setFont(font)
        self.triangle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/triangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triangle.setIcon(icon3)
        self.triangle.setIconSize(QtCore.QSize(116, 102))
        self.triangle.setFlat(True)
        self.triangle.setObjectName("triangle")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(0, 102, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(190, 210, 120, 141))
        self.widget_4.setObjectName("widget_4")
        self.rectangle = QtWidgets.QPushButton(self.widget_4)
        self.rectangle.setGeometry(QtCore.QRect(0, 0, 121, 131))
        font = QtGui.QFont()
        self.rectangle.setFont(font)
        self.rectangle.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectangle.setIcon(icon4)
        self.rectangle.setIconSize(QtCore.QSize(124, 138))
        self.rectangle.setFlat(True)
        self.rectangle.setObjectName("rectangle")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(0, 102, 121, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.setup_buttons()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def square_window(self):
        Form = QtWidgets.QWidget()
        self.window4 = QtWidgets.QMainWindow()
        self.ui1 = UiForm()
        self.ui1.setupUi(self.window4)
        self.window4.show()
        Form.hide()
    
    def circle_window(self):
        Form = QtWidgets.QWidget()
        self.window5 = QtWidgets.QMainWindow()
        self.ui1 = UForm()
        self.ui1.setupUi(self.window5)
        self.window5.show()
        Form.hide()

    def triangle_window(self):
        Form = QtWidgets.QWidget()
        self.window6 = QtWidgets.QMainWindow()
        self.ui1 = iForm()
        self.ui1.setupUi(self.window6)
        self.window6.show()
        Form.hide()

    def rectangle_window(self):
        Form = QtWidgets.QWidget()
        self.window7 = QtWidgets.QMainWindow()
        self.ui1 = U_Form()
        self.ui1.setupUi(self.window7)
        self.window7.show()
        Form.hide()

    def setup_buttons(self):
        self.square.clicked.connect(self.square_window)
        self.circle.clicked.connect(self.circle_window)
        self.triangle.clicked.connect(self.triangle_window)
        self.rectangle.clicked.connect(self.rectangle_window)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("area", "area"))
        self.label.setText(_translate("Form", "Choose Shape"))
        self.label_2.setText(_translate("Form", "Square"))
        self.label_3.setText(_translate("Form", "Circle"))
        self.label_4.setText(_translate("Form", "Tri-Angle"))
        self.label_5.setText(_translate("Form", "Rectangle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = area()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
