# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'circle-area.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(225, 250)
        Form.setMinimumSize(QtCore.QSize(225, 250))
        Form.setMaximumSize(QtCore.QSize(225, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(26, 40, 171, 27))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 80, 191, 41))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 156, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 255, 0);")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.calculate)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def calculate(self):
        radius = self.lineEdit.text()
        area = 3.14*float(radius)*float(radius)
        self.label.setText(f"Area of circle = {str(area)}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "circle-area"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter circle radius"))
        self.label.setText(_translate("Form", "Area of circle = "))
        self.pushButton.setText(_translate("Form", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
